version: "3"

################################################################################################

tasks:
  echo:
    cmds:
      - echo {{.CLI_ARGS}}

  r:
    cmds:
      - swift run

  t:
    cmds:
      - swift test